{
   "total_size":1936,
   "start":0,
   "entries":[
      {
         "date_closed":"2011-09-02T10:42:43.883929+00:00",
         "date_assigned":null,
         "title":"Bug #839461 in Bazaar: \"can't run selftest for 2.2 with recent subunit/testtools\"",
         "bug_link":"https://api.launchpad.net/1.0/bugs/839461",
         "bug_watch_link":null,
         "milestone_link":null,
         "http_etag":"\"7637a30eacaf5ecb72de984cade968b8fa71f254-d972cf0e7d92bfe2254297a6f6615e71e6dd0184\"",
         "date_left_closed":null,
         "date_fix_committed":null,
         "date_fix_released":null,
         "date_in_progress":null,
         "resource_type_link":"https://api.launchpad.net/1.0/#bug_task",
         "status":"Confirmed",
         "bug_target_name":"bzr",
         "importance":"Critical",
         "assignee_link":null,
         "date_triaged":null,
         "self_link":"https://api.launchpad.net/1.0/bzr/+bug/839461",
         "target_link":"https://api.launchpad.net/1.0/bzr",
         "bug_target_display_name":"Bazaar",
         "related_tasks_collection_link":"https://api.launchpad.net/1.0/bzr/+bug/839461/related_tasks",
         "date_confirmed":"2011-09-02T10:46:28.553673+00:00",
         "date_left_new":"2011-09-02T10:46:28.553673+00:00",
         "web_link":"https://bugs.launchpad.net/bzr/+bug/839461",
         "owner_link":"https://api.launchpad.net/1.0/~vila",
         "date_created":"2011-09-02T10:42:43.883929+00:00",
         "date_incomplete":null,
         "is_complete":false
      }
  ]
}
